/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppModuleRouteImport } from './routes/app/$module'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppModuleIdRouteImport } from './routes/app/$module.$id'
import { Route as V1AdminSplatRouteImport } from './routes/v1/admin/$'
import { Route as V1AdminResourceIdRouteImport } from './routes/v1/admin/$resource.$id'
import { Route as V1AdminDispatchReassignRouteImport } from './routes/v1/admin/dispatch/reassign'
import { Route as V1AdminCustomerOrderRouteImport } from './routes/v1/admin/customer-order'
import { Route as V1AdminCustomerOrdersRouteImport } from './routes/v1/admin/customer-orders'
import { Route as V1AdminOrdersIdRiderTransitionRouteImport } from './routes/v1/admin/orders/$id/rider-transition'
import { Route as V1AdminRiderOffersRouteImport } from './routes/v1/admin/rider-offers'
import { Route as V1PaymentsSplatRouteImport } from './routes/v1/payments/$'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const AppRouteRoute = AppRouteRouteImport.update({ id: '/app', path: '/app', getParentRoute: () => rootRouteImport } as any)
const LoginRoute = LoginRouteImport.update({ id: '/login', path: '/login', getParentRoute: () => rootRouteImport } as any)
const AppIndexRoute = AppIndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => AppRouteRoute } as any)
const AppModuleRoute = AppModuleRouteImport.update({ id: '/$module', path: '/$module', getParentRoute: () => AppRouteRoute } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({ id: '/api/auth/$', path: '/api/auth/$', getParentRoute: () => rootRouteImport } as any)
const AppModuleIdRoute = AppModuleIdRouteImport.update({ id: '/$id', path: '/$id', getParentRoute: () => AppModuleRoute } as any)
const V1AdminSplatRoute = V1AdminSplatRouteImport.update({ id: '/v1/admin/$', path: '/v1/admin/$', getParentRoute: () => rootRouteImport } as any)
const V1AdminResourceIdRoute = V1AdminResourceIdRouteImport.update({ id: '/v1/admin/$resource/$id', path: '/v1/admin/$resource/$id', getParentRoute: () => rootRouteImport } as any)
const V1AdminDispatchReassignRoute = V1AdminDispatchReassignRouteImport.update({ id: '/v1/admin/dispatch/reassign', path: '/v1/admin/dispatch/reassign', getParentRoute: () => rootRouteImport } as any)
const V1AdminCustomerOrderRoute = V1AdminCustomerOrderRouteImport.update({ id: '/v1/admin/customer-order', path: '/v1/admin/customer-order', getParentRoute: () => rootRouteImport } as any)
const V1AdminCustomerOrdersRoute = V1AdminCustomerOrdersRouteImport.update({ id: '/v1/admin/customer-orders', path: '/v1/admin/customer-orders', getParentRoute: () => rootRouteImport } as any)
const V1AdminOrdersIdRiderTransitionRoute = V1AdminOrdersIdRiderTransitionRouteImport.update({ id: '/v1/admin/orders/$id/rider-transition', path: '/v1/admin/orders/$id/rider-transition', getParentRoute: () => rootRouteImport } as any)
const V1AdminRiderOffersRoute = V1AdminRiderOffersRouteImport.update({ id: '/v1/admin/rider-offers', path: '/v1/admin/rider-offers', getParentRoute: () => rootRouteImport } as any)
const V1PaymentsSplatRoute = V1PaymentsSplatRouteImport.update({ id: '/v1/payments/$', path: '/v1/payments/$', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/$module': typeof AppModuleRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$module/$id': typeof AppModuleIdRoute
  '/v1/admin/$': typeof V1AdminSplatRoute
  '/v1/admin/$resource/$id': typeof V1AdminResourceIdRoute
  '/v1/admin/dispatch/reassign': typeof V1AdminDispatchReassignRoute
  '/v1/admin/customer-order': typeof V1AdminCustomerOrderRoute
  '/v1/admin/customer-orders': typeof V1AdminCustomerOrdersRoute
  '/v1/admin/orders/$id/rider-transition': typeof V1AdminOrdersIdRiderTransitionRoute
  '/v1/admin/rider-offers': typeof V1AdminRiderOffersRoute
  '/v1/payments/$': typeof V1PaymentsSplatRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/$module': typeof AppModuleRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$module/$id': typeof AppModuleIdRoute
  '/v1/admin/$': typeof V1AdminSplatRoute
  '/v1/admin/$resource/$id': typeof V1AdminResourceIdRoute
  '/v1/admin/dispatch/reassign': typeof V1AdminDispatchReassignRoute
  '/v1/admin/customer-order': typeof V1AdminCustomerOrderRoute
  '/v1/admin/customer-orders': typeof V1AdminCustomerOrdersRoute
  '/v1/admin/orders/$id/rider-transition': typeof V1AdminOrdersIdRiderTransitionRoute
  '/v1/admin/rider-offers': typeof V1AdminRiderOffersRoute
  '/v1/payments/$': typeof V1PaymentsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: keyof FileRoutesByFullPath
  fileRoutesByTo: FileRoutesByTo
  to: keyof FileRoutesByFullPath
  id: keyof FileRoutesById
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  V1AdminSplatRoute: typeof V1AdminSplatRoute
  V1AdminResourceIdRoute: typeof V1AdminResourceIdRoute
  V1AdminDispatchReassignRoute: typeof V1AdminDispatchReassignRoute
  V1AdminCustomerOrderRoute: typeof V1AdminCustomerOrderRoute
  V1AdminCustomerOrdersRoute: typeof V1AdminCustomerOrdersRoute
  V1AdminOrdersIdRiderTransitionRoute: typeof V1AdminOrdersIdRiderTransitionRoute
  V1AdminRiderOffersRoute: typeof V1AdminRiderOffersRoute
  V1PaymentsSplatRoute: typeof V1PaymentsSplatRoute
}

interface AppModuleRouteChildren { AppModuleIdRoute: typeof AppModuleIdRoute }
const AppModuleRouteChildren: AppModuleRouteChildren = { AppModuleIdRoute }
const AppModuleRouteWithChildren = AppModuleRoute._addFileChildren(AppModuleRouteChildren)

interface AppRouteRouteChildren {
  AppModuleRoute: typeof AppModuleRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}
const AppRouteRouteChildren: AppRouteRouteChildren = { AppModuleRoute: AppModuleRouteWithChildren, AppIndexRoute }
const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(AppRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute,
  ApiAuthSplatRoute,
  V1AdminSplatRoute,
  V1AdminResourceIdRoute,
  V1AdminDispatchReassignRoute,
  V1AdminCustomerOrderRoute,
  V1AdminCustomerOrdersRoute,
  V1AdminOrdersIdRiderTransitionRoute,
  V1AdminRiderOffersRoute,
  V1PaymentsSplatRoute,
}

export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
