/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppModuleRouteImport } from './routes/app/$module'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppModuleIdRouteImport } from './routes/app/$module.$id'
import { Route as V1AdminSplatRouteImport } from './routes/v1/admin/$'
import { Route as V1AdminResourceIdRouteImport } from './routes/v1/admin/$resource.$id'
import { Route as V1AdminDispatchReassignRouteImport } from './routes/v1/admin/dispatch/reassign'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppModuleRoute = AppModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppModuleIdRoute = AppModuleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppModuleRoute,
} as any)
const V1AdminSplatRoute = V1AdminSplatRouteImport.update({
  id: '/v1/admin/$',
  path: '/v1/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AdminResourceIdRoute = V1AdminResourceIdRouteImport.update({
  id: '/v1/admin/$resource/$id',
  path: '/v1/admin/$resource/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AdminDispatchReassignRoute = V1AdminDispatchReassignRouteImport.update({
  id: '/v1/admin/dispatch/reassign',
  path: '/v1/admin/dispatch/reassign',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/$module': typeof AppModuleRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$module/$id': typeof AppModuleIdRoute
  '/v1/admin/$': typeof V1AdminSplatRoute
  '/v1/admin/$resource/$id': typeof V1AdminResourceIdRoute
  '/v1/admin/dispatch/reassign': typeof V1AdminDispatchReassignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/$module': typeof AppModuleRouteWithChildren
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$module/$id': typeof AppModuleIdRoute
  '/v1/admin/$': typeof V1AdminSplatRoute
  '/v1/admin/$resource/$id': typeof V1AdminResourceIdRoute
  '/v1/admin/dispatch/reassign': typeof V1AdminDispatchReassignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/$module': typeof AppModuleRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$module/$id': typeof AppModuleIdRoute
  '/v1/admin/$': typeof V1AdminSplatRoute
  '/v1/admin/$resource/$id': typeof V1AdminResourceIdRoute
  '/v1/admin/dispatch/reassign': typeof V1AdminDispatchReassignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/$module'
    | '/app/'
    | '/api/auth/$'
    | '/app/$module/$id'
    | '/v1/admin/$'
    | '/v1/admin/$resource/$id'
    | '/v1/admin/dispatch/reassign'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/$module'
    | '/app'
    | '/api/auth/$'
    | '/app/$module/$id'
    | '/v1/admin/$'
    | '/v1/admin/$resource/$id'
    | '/v1/admin/dispatch/reassign'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/$module'
    | '/app/'
    | '/api/auth/$'
    | '/app/$module/$id'
    | '/v1/admin/$'
    | '/v1/admin/$resource/$id'
    | '/v1/admin/dispatch/reassign'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  V1AdminSplatRoute: typeof V1AdminSplatRoute
  V1AdminResourceIdRoute: typeof V1AdminResourceIdRoute
  V1AdminDispatchReassignRoute: typeof V1AdminDispatchReassignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$module': {
      id: '/app/$module'
      path: '/$module'
      fullPath: '/app/$module'
      preLoaderRoute: typeof AppModuleRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$module/$id': {
      id: '/app/$module/$id'
      path: '/$id'
      fullPath: '/app/$module/$id'
      preLoaderRoute: typeof AppModuleIdRouteImport
      parentRoute: typeof AppModuleRoute
    }
    '/v1/admin/$': {
      id: '/v1/admin/$'
      path: '/v1/admin/$'
      fullPath: '/v1/admin/$'
      preLoaderRoute: typeof V1AdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/admin/$resource/$id': {
      id: '/v1/admin/$resource/$id'
      path: '/v1/admin/$resource/$id'
      fullPath: '/v1/admin/$resource/$id'
      preLoaderRoute: typeof V1AdminResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/admin/dispatch/reassign': {
      id: '/v1/admin/dispatch/reassign'
      path: '/v1/admin/dispatch/reassign'
      fullPath: '/v1/admin/dispatch/reassign'
      preLoaderRoute: typeof V1AdminDispatchReassignRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppModuleRouteChildren {
  AppModuleIdRoute: typeof AppModuleIdRoute
}

const AppModuleRouteChildren: AppModuleRouteChildren = {
  AppModuleIdRoute: AppModuleIdRoute,
}

const AppModuleRouteWithChildren = AppModuleRoute._addFileChildren(
  AppModuleRouteChildren,
)

interface AppRouteRouteChildren {
  AppModuleRoute: typeof AppModuleRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppModuleRoute: AppModuleRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  V1AdminSplatRoute: V1AdminSplatRoute,
  V1AdminResourceIdRoute: V1AdminResourceIdRoute,
  V1AdminDispatchReassignRoute: V1AdminDispatchReassignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
